import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Root Layout is the outermost layout that wraps all pages
// Root Layout need html and body tags
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className={'p-2'}> root layout need html and body tags </h1>
        {children}
      </body>
    </html>
  )
}
